### ISSUE TITLE
Test `it_should_make_a_connection_cookie` failing with `rustc 1.75.0-nightly (7adc89b69 2023-11-07)`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#502] opened 2023-11-08 12:28 UTC
```console
---- servers::udp::connection_cookie::tests::it_should_make_a_connection_cookie stdout ----
thread 'servers::udp::connection_cookie::tests::it_should_make_a_connection_cookie' panicked at src/servers/udp/connection_cookie.rs:180:9:
assertion `left == right` failed
  left: [41, 166, 45, 246, 249, 24, 108, 203]
 right: [23, 204, 198, 29, 48, 180, 62, 19]


failures:
    servers::udp::connection_cookie::tests::it_should_make_a_connection_cookie

test result: FAILED. 264 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.19s
```

**Comment by da2ce7** [comment] 2023-11-08 15:26
fixed by #501
I believe it was caused by the hash algorithm changing slightly in the new builds of rust, and therefore our hardcoded value being incorrect for these new builds; fixed by making it match either the old or new version:
https://github.com/torrust/torrust-tracker/commit/dbc8920c70f6a78abf71fc86d421828d7970bbaa#diff-5b0ef826bf468095b9610a960ecad4fec2d6630217b44f29f33a7121e79c3a98

**Closed as completed by da2ce7** 2023-11-08 15:26 UTC
Labels: Bug
